apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pingwazi
  name: gocode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gocode
  template:
    metadata:
      labels:
        app: gocode
    spec:
      imagePullSecrets:
        - name: pwz-secret
      containers:
        - name: gocode
          env:
            - name: ENV
              value: prod
          image: pingwazi0101/imagename
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
